"""Add movie_id to reviews

Revision ID: 1fc49dea631f
Revises: fbbc2abd7461
Create Date: 2025-04-13 21:49:30.895318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc49dea631f'
down_revision = 'fbbc2abd7461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('movie_id')

    # ### end Alembic commands ###
